### ISSUE TITLE
Remove dependency on url module in browser environments

### ISSUE THREAD

**Issue by mrlika** [webtorrent/bittorrent-tracker#326]
https://github.com/webtorrent/bittorrent-tracker/blob/1a075bd15947b068d74e2b3c65c84ddc523a40e7/client.js#L8

`require('url')` is a big module that also depneds on another not small module `punnycode`.

`url` module is redundant in browser environments. Compatible [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) object already exists in the global scope there. Removing it significantly reduces output size of web bundles.

Can this `require` somehow be removed in browser environments?

**Comment by feross** [comment]
Yes, I plan to do this. See this issue to track the progress: https://github.com/webtorrent/webtorrent/issues/1681

**Comment by guanzo** [comment]
`const URL = require('url').URL`  is not a valid export when this package is built with webpack (and browserify too I think). The shim package exports `Url` instead of `URL`.

https://github.com/defunctzombie/node-url/issues/37

This error should go away when you drop the require, but wanted to let you know the current build will break when built by bundlers.

**Comment by feross** [comment]
Fixed in https://github.com/webtorrent/bittorrent-tracker/commit/93b41391a95546b11bceb1ee0d5b44f4c6a71592 and will go out in the next release.
