### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by misi** [webtorrent/bittorrent-tracker#334]
1. _What problem do you want to solve?_
  Have a private torrent tracker in docker.
  I want to use it with multipartymeeting:
    - https://github.com/misi/mm
    - https://hub.docker.com/r/misi/mm/

2. _What do you think is the correct solution to this problem?_
  Dockerize bittorent-tracker

3. _Are you willing to submit a pull request to implement this change?_
  Yes.

**Comment by mtib** [comment]
```dockerfile
FROM node:12
RUN npm install -g bittorrent-tracker
EXPOSE 8000
CMD ["bittorrent-tracker"]
```

```bash
#!/bin/bash

docker run -d --name bittorrent-tracker --restart=unless-stopped -p 6969:8000 -p 6969:8000/udp bittorrent-tracker
```

**Comment by feross** [comment]
Thanks for reporting this issue. Due to time constraints, I don't have any plans to work on this so I'm going to close it. If you would like to see it implemented, please send a pull request!

You might want to look at the `Dockerfile` that was recently submitted to `webtorrent-hybrid` for inspiration: https://github.com/webtorrent/webtorrent-hybrid/pull/110
